# Generated by Django 2.2.24 on 2023-07-16 21:29

from django.db import migrations


def fills_model_data(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_owner'),
    ]

    operations = [
        migrations.RunPython(fills_model_data)
    ]
