# Generated by Django 2.2.24 on 2023-07-17 00:42

from django.db import migrations


def connects_flats_with_owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner_flats = Flat.objects.filter(owner=owner.owner)
        if owner_flats.exists():
            owner.possessions.set(owner_flats)
            owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20230717_0421'),
    ]

    operations = [
        migrations.RunPython(connects_flats_with_owners)
    ]
