# Generated by Django 2.2.24 on 2023-07-18 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0012_auto_20230718_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='likes',
        ),
        migrations.AddField(
            model_name='flat',
            name='who_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critics', to='property.Flat', verbose_name='Квартира,на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
