# Generated by Django 2.2.24 on 2023-07-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230718_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='possessions',
            new_name='flats',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='owner_phonenumber',
        ),
    ]
